### ISSUE TITLE
The loading got stuck at plan_ssbn_xia

### ISSUE THREAD

**Issue by ZTZ-99B** [Dot-M134/ColdWaters-DotMod#12]
![3{@V7B_)GZ V~S9HX4 8K68](https://user-images.githubusercontent.com/53068857/127582204-bd4e46dd-ce12-41ae-b524-76f467cfb79a.png)

**Comment by HobbitJack** [comment]
Need an output_log.txt at debug level 3 to look at this further

**Comment by HobbitJack** [comment]
@ZTZ-99B Please attach an output log within 24 hours or I will close the issue.

**Comment by ZTZ-99B** [comment]
> @ZTZ-99B Please attach an output log within 26 hours or I will close the issue.

Reinstalled the game and now the problem has been solved, the issue can be closed. :)
