### ISSUE TITLE
Mission 5, 6, 7, 18 Description in English on Russian Language

### ISSUE THREAD

**Issue by FirebarSim** [Dot-M134/ColdWaters-DotMod#14]
https://discord.com/channels/824084038394445824/866120539512373268/870643614865293383

**Comment by Russian-Wolf** [comment]
Here I have a translation. It's not perfect, but I tried my best.
[single018.txt](https://github.com/Dot-M134/ColdWaters-DotMod/files/6908452/single018.txt)
[single005.txt](https://github.com/Dot-M134/ColdWaters-DotMod/files/6908453/single005.txt)
[single006.txt](https://github.com/Dot-M134/ColdWaters-DotMod/files/6908454/single006.txt)
[single007.txt](https://github.com/Dot-M134/ColdWaters-DotMod/files/6908455/single007.txt)
