### ISSUE TITLE
Missions 10 to 16 no translations to Russian

### ISSUE THREAD

**Issue by FirebarSim** [Dot-M134/ColdWaters-DotMod#15]
https://discord.com/channels/824084038394445824/866120539512373268/870643614865293383

**Comment by Russian-Wolf** [comment]
Translated:
[missions_single.txt](https://github.com/Dot-M134/ColdWaters-DotMod/files/6909854/missions_single.txt)
[single010.txt](https://github.com/Dot-M134/ColdWaters-DotMod/files/6909855/single010.txt)
[single014.txt](https://github.com/Dot-M134/ColdWaters-DotMod/files/6909857/single014.txt)
[single015.txt](https://github.com/Dot-M134/ColdWaters-DotMod/files/6909858/single015.txt)
[single016.txt](https://github.com/Dot-M134/ColdWaters-DotMod/files/6909859/single016.txt)
[single011.txt](https://github.com/Dot-M134/ColdWaters-DotMod/files/6909860/single011.txt)
[single012.txt](https://github.com/Dot-M134/ColdWaters-DotMod/files/6909861/single012.txt)
[single013.txt](https://github.com/Dot-M134/ColdWaters-DotMod/files/6909862/single013.txt)
