### ISSUE TITLE
Game Freeze on Quick Mission under Ice

### ISSUE THREAD

**Issue by FirebarSim** [Dot-M134/ColdWaters-DotMod#2]
Don't know if this has been posted before, but when I do a quick mission via the editor and it is under the ice (very northern part of the map), the game freezes after I got to select my vessel (I tried to select different subs) and before the "All hands battle station" screen. The screen goes blank (actually only shows one blue / greenish colour) and then I have to Alt-F4
[output_log (14).txt](https://github.com/Dot-M134/ColdWaters-DotMod/files/6880991/output_log.14.txt)

**Comment by Dot-M134** [comment]
Fixed.
