### ISSUE TITLE
IndexOutOfRangeException: Array index is out of range at CampaignManager.GetTaskForceNextWaypoint

### ISSUE THREAD

**Issue by HobbitJack** [Dot-M134/ColdWaters-DotMod#25]
A waypoint issue is present in presumably all NATO campaigns that has the high likelihood of bricking save files. Until this issue is solved, I will ask that any logs showing the above error are posted here while I try to collect more data.
[output_log.txt](https://github.com/Dot-M134/ColdWaters-DotMod/files/6910495/output_log.txt)
[output_log (1).txt](https://github.com/Dot-M134/ColdWaters-DotMod/files/6910504/output_log.1.txt)
[output_log (2).txt](https://github.com/Dot-M134/ColdWaters-DotMod/files/6910505/output_log.2.txt)

**Comment by HobbitJack** [comment]
[output_log (3).txt](https://github.com/Dot-M134/ColdWaters-DotMod/files/6910506/output_log.3.txt)

**Comment by HobbitJack** [comment]
This issue should be fixed in v0.1e.
Will re-open if the issue persists.

**Comment by HobbitJack** [comment]
[output_log.txt](https://github.com/Dot-M134/ColdWaters-DotMod/files/6917417/output_log.txt)

**Comment by Dot-M134** [comment]
Should be fixed in 0.1f Need feedback

**Comment by HobbitJack** [comment]
Seems to be working.
