### ISSUE TITLE
Menu Issues on ultrawide displays

### ISSUE THREAD

**Issue by HobbitJack** [Dot-M134/ColdWaters-DotMod#26]
The main menu seems to not like ultrawide displays.
https://discord.com/channels/824084038394445824/866120539512373268/870753913568124948

**Comment by DavidP2045** [comment]
The menu is all messed up on an ultra-wide display (5120x1440). The settings are inaccessible and the in-engagement map view can also be improved.

**Comment by jcodling** [comment]
Same here at 3880 x 1440. It must be really bad on an even wider display.
