### ISSUE TITLE
Linux on both Steam and Lutris launcher hangs forever on "Validation file... resources.assets.resS"

### ISSUE THREAD

**Issue by devnull77** [Dot-M134/ColdWaters-DotMod#31]

**Comment by devnull77** [comment]
Here is:


Initialize engine version: 5.4.0f3 (a6d8d714de6f)
GfxDevice: creating device client; threaded=1
info:  Game: ColdWaters.exe
info:  DXVK: v1.9.1-3-geb95a9fb
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  Skipping Vulkan 1.0 adapter: llvmpipe (LLVM 12.0.0, 256 bits)
warn:  D3D9: VK_FORMAT_D16_UNORM_S8_UINT -> VK_FORMAT_D24_UNORM_S8_UINT
info:  NVIDIA GeForce GTX 1650 Ti:
info:    Driver: 470.57.2
info:    Vulkan: 1.2.175
info:    Memory Heap[0]: 
info:      Size: 4096 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 11575 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[8]: Property Flags = 0x6
info:      Memory Type[9]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 246 MiB
info:      Flags: 0x1
info:      Memory Type[10]: Property Flags = 0x7
info:  Process set as DPI aware
info:  Game: ColdWaters.exe
info:  DXVK: v1.9.1-3-geb95a9fb
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
info:    OpenXR
info:  OpenVR: could not open registry key, status 2
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
warn:  Skipping Vulkan 1.0 adapter: llvmpipe (LLVM 12.0.0, 256 bits)
info:  NVIDIA GeForce GTX 1650 Ti:
info:    Driver: 470.57.2
info:    Vulkan: 1.2.175
info:    Memory Heap[0]: 
info:      Size: 4096 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 11575 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[8]: Property Flags = 0x6
info:      Memory Type[9]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 246 MiB
info:      Flags: 0x1
info:      Memory Type[10]: Property Flags = 0x7
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
info:  Adapter LUID 0: 0:3f5
Direct3D:
    Version:  Direct3D 9.0c [nvd3dum.dll 32767.65535.65535.65535]
    Renderer: NVIDIA GeForce GTX 1650 Ti
    Vendor:   NVIDIA
    VRAM:     3072 MB (via DXGI)
warn:  ConvertFormat: Unknown format encountered: -1
warn:  ConvertFormat: Unknown format encountered: -1
warn:  ConvertFormat: Unknown format encountered: -1
warn:  ConvertFormat: Unknown format encountered: -1
warn:  ConvertFormat: Unknown format encountered: -1
warn:  ConvertFormat: Unknown format encountered: -1
    Caps:     Shader=30 DepthRT=1 NativeDepth=1 NativeShadow=1 DF16=1 INTZ=1 NULL=1 RESZ=1 SlowINTZ=0 ATOC=1
info:  Device properties:
info:    Device name:     : NVIDIA GeForce GTX 1650 Ti
info:    Driver version   : 470.57.2
info:  Enabled device extensions:
info:    VK_EXT_4444_formats
info:    VK_EXT_conservative_rasterization
info:    VK_EXT_custom_border_color
info:    VK_EXT_depth_clip_enable
info:    VK_EXT_extended_dynamic_state
info:    VK_EXT_host_query_reset
info:    VK_EXT_robustness2
info:    VK_EXT_shader_demote_to_helper_invocation
info:    VK_EXT_shader_viewport_index_layer
info:    VK_EXT_transform_feedback
info:    VK_EXT_vertex_attribute_divisor
info:    VK_KHR_create_renderpass2
info:    VK_KHR_depth_stencil_resolve
info:    VK_KHR_draw_indirect_count
info:    VK_KHR_driver_properties
info:    VK_KHR_image_format_list
info:    VK_KHR_sampler_mirror_clamp_to_edge
info:    VK_KHR_shader_float_controls
info:    VK_KHR_swapchain
info:  Device features:
info:    robustBufferAccess                     : 1
info:    fullDrawIndexUint32                    : 1
info:    imageCubeArray                         : 1
info:    independentBlend                       : 1
info:    geometryShader                         : 1
info:    tessellationShader                     : 0
info:    sampleRateShading                      : 1
info:    dualSrcBlend                           : 0
info:    logicOp                                : 0
info:    multiDrawIndirect                      : 0
info:    drawIndirectFirstInstance              : 0
info:    depthClamp                             : 1
info:    depthBiasClamp                         : 1
info:    fillModeNonSolid                       : 1
info:    depthBounds                            : 1
info:    multiViewport                          : 1
info:    samplerAnisotropy                      : 1
info:    textureCompressionBC                   : 1
info:    occlusionQueryPrecise                  : 1
info:    pipelineStatisticsQuery                : 1
info:    vertexPipelineStoresAndAtomics         : 1
info:    fragmentStoresAndAtomics               : 0
info:    shaderImageGatherExtended              : 0
info:    shaderStorageImageExtendedFormats      : 0
info:    shaderStorageImageReadWithoutFormat    : 0
info:    shaderStorageImageWriteWithoutFormat   : 1
info:    shaderClipDistance                     : 1
info:    shaderCullDistance                     : 1
info:    shaderFloat64                          : 0
info:    shaderInt64                            : 0
info:    variableMultisampleRate                : 0
info:  VK_EXT_4444_formats
info:    formatA4R4G4B4                         : 1
info:    formatA4B4G4R4                         : 1
info:  VK_EXT_custom_border_color
info:    customBorderColors                     : 1
info:    customBorderColorWithoutFormat         : 1
info:  VK_EXT_depth_clip_enable
info:    depthClipEnable                        : 1
info:  VK_EXT_extended_dynamic_state
info:    extendedDynamicState                   : 1
info:  VK_EXT_host_query_reset
info:    hostQueryReset                         : 1
info:  VK_EXT_memory_priority
info:    memoryPriority                         : 0
info:  VK_EXT_robustness2
info:    robustBufferAccess2                    : 1
info:    robustImageAccess2                     : 0
info:    nullDescriptor                         : 1
info:  VK_EXT_shader_demote_to_helper_invocation
info:    shaderDemoteToHelperInvocation         : 1
info:  VK_EXT_transform_feedback
info:    transformFeedback                      : 0
info:    geometryStreams                        : 0
info:  VK_EXT_vertex_attribute_divisor
info:    vertexAttributeInstanceRateDivisor     : 1
info:    vertexAttributeInstanceRateZeroDivisor : 1
info:  Queue families:
info:    Graphics : 0
info:    Transfer : 1
info:  DXVK: Read 451 valid state cache entries
info:  DXVK: Using 7 compiler threads
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              312
info:      - Height:             213
info:      - Format:             D3D9Format::A8R8G8B8
info:      - Auto Depth Stencil: false
info:                  ^ Format: D3D9Format::D24S8
info:      - Windowed:           true
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  312x213
info:    Image count:  2
info:    Exclusive FS: 0
Begin MonoManager ReloadAssembly
Platform assembly: C:\GOG Games\Cold Waters\ColdWaters_Data\Managed\UnityEngine.dll (this message is harmless)
Loading C:\GOG Games\Cold Waters\ColdWaters_Data\Managed\UnityEngine.dll into Unity Child Domain
Platform assembly: C:\GOG Games\Cold Waters\ColdWaters_Data\Managed\Assembly-CSharp-firstpass.dll (this message is harmless)
Loading C:\GOG Games\Cold Waters\ColdWaters_Data\Managed\Assembly-CSharp-firstpass.dll into Unity Child Domain
Platform assembly: C:\GOG Games\Cold Waters\ColdWaters_Data\Managed\Assembly-CSharp.dll (this message is harmless)
Loading C:\GOG Games\Cold Waters\ColdWaters_Data\Managed\Assembly-CSharp.dll into Unity Child Domain
Platform assembly: C:\GOG Games\Cold Waters\ColdWaters_Data\Managed\Assembly-UnityScript-firstpass.dll (this message is harmless)
Loading C:\GOG Games\Cold Waters\ColdWaters_Data\Managed\Assembly-UnityScript-firstpass.dll into Unity Child Domain
Platform assembly: C:\GOG Games\Cold Waters\ColdWaters_Data\Managed\UnityEngine.UI.dll (this message is harmless)
Loading C:\GOG Games\Cold Waters\ColdWaters_Data\Managed\UnityEngine.UI.dll into Unity Child Domain
Platform assembly: C:\GOG Games\Cold Waters\ColdWaters_Data\Managed\UnityEngine.Networking.dll (this message is harmless)
Loading C:\GOG Games\Cold Waters\ColdWaters_Data\Managed\UnityEngine.Networking.dll into Unity Child Domain
Platform assembly: C:\GOG Games\Cold Waters\ColdWaters_Data\Managed\AmplifyBloom.dll (this message is harmless)
Loading C:\GOG Games\Cold Waters\ColdWaters_Data\Managed\AmplifyBloom.dll into Unity Child Domain
Platform assembly: C:\GOG Games\Cold Waters\ColdWaters_Data\Managed\AmplifyColor.dll (this message is harmless)
Loading C:\GOG Games\Cold Waters\ColdWaters_Data\Managed\AmplifyColor.dll into Unity Child Domain
Platform assembly: C:\GOG Games\Cold Waters\ColdWaters_Data\Managed\AmplifyOcclusion.dll (this message is harmless)
Loading C:\GOG Games\Cold Waters\ColdWaters_Data\Managed\AmplifyOcclusion.dll into Unity Child Domain
- Completed reload, in  0.049 seconds
Platform assembly: C:\GOG Games\Cold Waters\ColdWaters_Data\Managed\System.Core.dll (this message is harmless)
Platform assembly: C:\GOG Games\Cold Waters\ColdWaters_Data\Managed\System.dll (this message is harmless)
Platform assembly: C:\GOG Games\Cold Waters\ColdWaters_Data\Managed\INIFileParser.dll (this message is harmless)
<RI> Initializing input.


<RI> Input initialized.


desktop: 1920x1080 120Hz; virtual: 1920x1080 at 0,0
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              1920
info:      - Height:             1080
info:      - Format:             D3D9Format::A8R8G8B8
info:      - Auto Depth Stencil: false
info:                  ^ Format: D3D9Format::D24S8
info:      - Windowed:           true
<RI> Touch support initialization failed: Wywołanie niezaimplementowane.


.


The file 'C:/GOG Games/Cold Waters/ColdWaters_Data/sharedassets0.assets' is corrupted! Remove it and launch unity again!
[Position out of bounds!]
 
(Filename:  Line: 223)

The file 'C:/GOG Games/Cold Waters/ColdWaters_Data/sharedassets0.assets' is corrupted! Remove it and launch unity again!
[Position out of bounds!]
 
(Filename:  Line: 223)

The file 'C:/GOG Games/Cold Waters/ColdWaters_Data/sharedassets0.assets' is corrupted! Remove it and launch unity again!
[Position out of bounds!]
 
(Filename:  Line: 223)

The file 'C:/GOG Games/Cold Waters/ColdWaters_Data/sharedassets0.assets' is corrupted! Remove it and launch unity again!
[Position out of bounds!]
 
(Filename:  Line: 223)

The file 'C:/GOG Games/Cold Waters/ColdWaters_Data/level0' is corrupted! Remove it and launch unity again!
[Position out of bounds!]
 
(Filename:  Line: 223)

The file 'C:/GOG Games/Cold Waters/ColdWaters_Data/level0' is corrupted! Remove it and launch unity again!
[Position out of bounds!]
 
(Filename:  Line: 223)

The file 'C:/GOG Games/Cold Waters/ColdWaters_Data/level0' is corrupted! Remove it and launch unity again!
[Position out of bounds!]
 
(Filename:  Line: 223)

The file 'C:/GOG Games/Cold Waters/ColdWaters_Data/level0' is corrupted! Remove it and launch unity again!
[Position out of bounds!]
 
(Filename:  Line: 223)

A script behaviour (probably PlayerFunctions?) has a different serialization layout when loading. (Read 2728 bytes but expected 2724 bytes)
Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?
 
(Filename:  Line: 1713)

The file 'C:/GOG Games/Cold Waters/ColdWaters_Data/level0' is corrupted! Remove it and launch unity again!
[Position out of bounds!]
 
(Filename:  Line: 223)

The file 'C:/GOG Games/Cold Waters/ColdWaters_Data/level0' is corrupted! Remove it and launch unity again!
[Position out of bounds!]
 
(Filename:  Line: 223)

The file 'C:/GOG Games/Cold Waters/ColdWaters_Data/level0' is corrupted! Remove it and launch unity again!
[Position out of bounds!]
 
(Filename:  Line: 223)

UnloadTime: 1.341100 ms
INFO: Options reports not validated, will validate now.
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_FIFO_KHR
info:    Buffer size:  1920x1080
info:    Image count:  3
info:    Exclusive FS: 0
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              1920
info:      - Height:             1080
info:      - Format:             D3D9Format::A8R8G8B8
info:      - Auto Depth Stencil: false
info:                  ^ Format: D3D9Format::D24S8
info:      - Windowed:           true
OutOfMemoryException: Out of memory
  at (wrapper managed-to-native) object:__icall_wrapper_mono_array_new_specific (intptr,int)
  at System.IO.File.ReadAllBytes (System.String path) [0x00000] in <filename unknown>:0 
  at TextParser+<ValidateFiles>d__1.MoveNext () [0x00000] in <filename unknown>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

Setting up 3 worker threads for Enlighten.
  Thread -> id: 24c -> priority: 1 
  Thread -> id: 254 -> priority: 1 
  Thread -> id: 250 -> priority: 1

**Comment by HobbitJack** [comment]
Seems to be a Linux issue. Normal game output logs don't look like this. Marked as unsolvable and closed.

**Comment by devnull77** [comment]
Maybe the option to disable validation could help? 
Is it possible to manually modify something so that this validation does not run?
