### ISSUE TITLE
Mk 48 ADCAP will point directly at the sea floor and explode

### ISSUE THREAD

**Issue by jcodling** [Dot-M134/ColdWaters-DotMod#35]
0.15e Beta

The weapon, with wire or not will just point straight down and explode after a random amount of time. The only thing I can think of is if there is a noise maker somewhere down there and no matter what it wants to follow it to its death. Since noise makers have no clipping with the bottom they sink forever. Even if they sat on the bottom I can see the weapon still trying to hit it and commit suicide.

Very frustrating but I also realize this is early beta. There is a lot of great stuff in this mod. Thank you all for your efforts.

**Comment by HobbitJack** [comment]
We'll see if we can take a look at it. I've heard the same thing about them popping to the surface.

**Comment by HobbitJack** [comment]
Need an output_log.txt with extended combat logging.

**Comment by HobbitJack** [comment]
Closing in 24h unless I get an output_log.txt

**Comment by jcodling** [comment]
Feel free. I don't have time to reinstall and you have already released a
new version that I will try soon. Hopefully it was just a fluke.
