### ISSUE TITLE
0.2a, instant towed array damage?!

### ISSUE THREAD

**Issue by Kingdud** [Dot-M134/ColdWaters-DotMod#38]
I installed 0.2a and for some reason, my towed array gets damaged the second I deploy it. I'm using a SeaWolf in the 2000s China campaign. I'm moving 5 knots and at a depth of 50 feet. I also tried at 200ft (in 430ft of water) and it instantly damaged there too. When I look in the output_log it says assets are corrupted. This is on a fresh install. Either something in the mod is corrupting that file or...idk. The ISO I used to install the base game hasn't changed, and I have the checksums to prove that. Any ideas?

[output_log.txt](https://github.com/Dot-M134/ColdWaters-DotMod/files/7118845/output_log.txt)

**Comment by NavyGuy658** [comment]
That is interesting. We'll look into it. Probably something that got changed by accident or something in that regard.

In regards to the corrupted assets, it is a side effect of recompiling the game scripts and is nothing to worry about.

**Comment by Dot-M134** [comment]
Wasnt able to replicate the issue at latest BE version.

**Comment by Kingdud** [comment]
[AutoSave.zip](https://github.com/Dot-M134/ColdWaters-DotMod/files/7144460/AutoSave.zip)
Perhaps my save file is corrupted? Any way to fix that other than to make a new game?

**Comment by HobbitJack** [comment]
Closing in 24h unless there is more info.
