### ISSUE TITLE
Civilian vessel material missing

### ISSUE THREAD

**Issue by FirebarSim** [Dot-M134/ColdWaters-DotMod#4]
One of the civilian vessels is missing a material.

**Comment by NavyGuy658** [comment]
This is a default issue too.

**Comment by FirebarSim** [comment]
ERROR: Unable to Load material from path: ships/civ_ms_roro/civ_ms_roro_deck

Verified that material is not included in default game

**Comment by FirebarSim** [comment]
Now in Stable
