### ISSUE TITLE
Audio callouts are using the wrong contact #

### ISSUE THREAD

**Issue by Werecow** [Dot-M134/ColdWaters-DotMod#44]
So far have just seen this on subs but Sierra 2 is always used even when the event involves Sierra 1, etc.  Text is right but the voice is not.

**Comment by Tarkalak** [comment]
I think this happens with cavitation message only and the callout will say the contact you have currently selected, whether it is the right on or not.

**Comment by HobbitJack** [comment]
Vanilla bug, but I'm sure we can look into it.

**Comment by HobbitJack** [comment]
Closing unless/until the issue re-appears.
