### ISSUE TITLE
Sovremmeny-class RBUs not working

### ISSUE THREAD

**Issue by Neko014** [Dot-M134/ColdWaters-DotMod#45]
The RBUs on the sovremmeny-class is not working even under 1km range, it says RBUs firing but nothing happened

**Comment by HobbitJack** [comment]
Seems to be a unit bug. Not surprised.

Reports fine while using Imperial, broken in Metric. Confirmed.

**Comment by HobbitJack** [comment]
Problem will be fixed in 0.2b.
