### ISSUE TITLE
Kilo recalled back to port after expending 1 torpedo

### ISSUE THREAD

**Issue by Tarkalak** [Dot-M134/ColdWaters-DotMod#46]
Version 0.2a

Soviet 1984 campaign.

The Kilo submarine is called back to Murmansk after each mission. Even when I expended a single torpedo. This haven't happened with other diesels.

**Comment by HobbitJack** [comment]
Need output_log.txt with campaign logging (available in Mod Settings\Developer Mode\Log Campaign) to make a determination.

**Comment by Tarkalak** [comment]
Is there a way to hack a new campaign to give me kapitan 1st rank faster so I can test it again?
I overwrite the original campaign.

**Comment by HobbitJack** [comment]
Need confirmation or closing in 24h

**Comment by Tarkalak** [comment]
I hacked the Kilo to be 0th rank to buy and couldn't reproduce it, so close it.

If I get it again I will submit a new one with logs.
