### ISSUE TITLE
Hunting the Arctic Wolf - Blue Screen 

### ISSUE THREAD

**Issue by NavyGuy658** [Dot-M134/ColdWaters-DotMod#5]
Note I had already converted the mission to fit 2004, but this was simply just adding different player vessels, and renaming some Soviet ones. The peculiar thing is that it crashed twice, but on my third attempt, I managed to get into combat and start the mission. I also managed to save the log.
[output_log.txt](https://github.com/Dot-M134/ColdWaters-DotMod/files/6885904/output_log.txt)

**Comment by HobbitJack** [comment]
This issue is the same as #2. Closed and marked as duplicate.
