### ISSUE TITLE
Strange cavitation Ohio SSBN

### ISSUE THREAD

**Issue by Antoine024** [Dot-M134/ColdWaters-DotMod#59]
https://gyazo.com/16f40144b689a72c48169388164caf4c
Hello guys ! 
Just a little report about a bug on the Ohio cavitation, it's on the sub (as you can see on the picture) 
Btw, thanks to all of you, i love your mod !

**Comment by FirebarSim** [comment]
This was due to the change from one model of the Ohio to another and is now fixed in bleeding edge and Hotfixed in 0.2b
