### ISSUE TITLE
Aggressive Error Screen

### ISSUE THREAD

**Issue by HobbitJack** [Dot-M134/ColdWaters-DotMod#6]
The new error screen reports campaign issues that should instead be regarded as warnings.
[output_log.txt](https://github.com/Dot-M134/ColdWaters-DotMod/files/6896043/output_log.txt)
![image0](https://user-images.githubusercontent.com/18198370/127385281-aead6043-c121-42f4-a35b-3daa097d80cb.jpg)

**Comment by FirebarSim** [comment]
`Debug.LogWarning( "WARNING: NO STARTS OR ENDS " + campaignmissions[arrayOfMissions[missionNumber]].missionFileName );`

and 

`Debug.LogWarning( "WARNING: TOO CLOSE TO PLAYER " + campaignmissions[arrayOfMissions[missionNumber]].missionFileName );`

Now in Bleeding Edge
