### ISSUE TITLE
Starting Issue

### ISSUE THREAD

**Issue by HobbitJack** [Dot-M134/ColdWaters-DotMod#9]
JohnnyHughes on the Discord seems to be having an issue with a "FormatException: Input string was not in the correct format" whenever he starts the game. Attached is his output_log.txt.
[output_log.txt](https://github.com/Dot-M134/ColdWaters-DotMod/files/6903293/output_log.txt)

**Comment by FirebarSim** [comment]
User reports having the Red Storm Rising Mod installed. Upon removing that all functioned correctly.
